### PR TITLE
AC97: Add support for SIS7012 (Fixes #27)

### LINKED ISSUE #27: SIS 7012 support
Already [posted on the Vogons thread](https://www.vogons.org/viewtopic.php?p=1197241#p1197241), but here for completeness and to track progress:

---

While looking for information on SIS7012, I found (as also mentioned in this thread) that it's mostly Intel ICH with some modifications. As I have a machine with a SIS7012, and sound output works great in Linux, I looked at the kernel sources. The SIS7012 driver is indeed implement in the same driver as the Intel ICH (sound/pci/intel8x0.c), and MPXPlay's sources also mention that it's based on ALSA (Linux driver) and ICH-DOS.

So, a quick look shows these changes are necessary between SIS7012 and "normal" ICH audio (refer to sound/pci/intel8x0.c in Linux):

- The channel mask bits (2, 4, 6 channels) in the global control block (register 0x2c) are different -- which is important for masking out the bits, but not important for setting bits, as SBEMU only uses 2-channel audio, and 2-channel audio is set by clearing the 4-channel and 6-channel bits -- that's ICH_PCM_246_MASK in both MPXPlay and Linux, Linux has the mask as ICH_SIS_PCM_246_MASK
- SIS7012 supports a "tertiary" codec with two additional flags (tertiary resume irq, tertiary codec ready)
- Linux assigns the device_type of DEVICE_SIS based on the PCI ID (MPXPlay has basically the same enum, the PCI ID is just commented out)
- In snd_intel8x0_setup_pcm_out(), the channel mask setting is different (see above)
- In snd_intel8x0_pcm_open(), both buffer_bytes_max and period_bytes_max are set to 64 KiB -- seems like we create smaller buffers anyway, so SBEMU is probably not affected by this
- In snd_intel8x0_ich_chip_init(), the LSB of register 0x4c is set, and the comment above it says "unmute the output on SIS7012", which is probably kind of important..
- Then, the ich_codec_bits[] has the tertiary for ICH4, but there's sis_codec_bits[] which has its own tertiary codec (ICH_SIS_TCR) bit
- In snd_intel8x0_init(), bdbars is 3 for DEVICE_INTEL and also 3 for DEVICE_SIS, so this is probably fine
SIS7012 swaps the PICB (position in current buffer, offset 0x08) and SR (status, offset 0x06) registers, this is put into "roff_sr" and "roff_picb" of the ichdev, and then used throughout; would need checking/updating to fix all the occurences and swap around
- ichdev->pos_shift is 1 (divided by two) for normal ICH, and 0 (no division by two) for SIS7012, the comment above says "SIS7012 handles the pcm data in bytes, others are in samples" -- this also needs to be handled, and is mostly relevant in setting up DMA and when retrieving the PCM pointer (for writing?), there's also some reference to it in intel8x0_measure_ac97_clock(), but this seems to be only relevant for chips with a clock quirk
- Then, when setting up max_codecs, codec_bit and codec_ready_bits, it also takes care of the tertiary codec, but it might work just fine with two codecs initialized (like normal ICH)
- And that's all the differences I can see in sound/pci/intel8x0.c.

I already tried patching and building a modified SBEMU, and it initializes and stuff, but no audio output is happening and PCM audio output locks up or cannot be initialized (SB emu side), OPL register writes seem to work, but again no audio output. Add to this some annoyances such as upper/lower case filenames and backslashes as path separator in #include directives, and compiling SBEMU on Linux is quite annoying (I use a recent DJGPP version to cross-compile on Linux).

Also, here's some debug output I get with my modified SBEMU (due to testing, some messages might not 100% match with the patch attached):

```
SBEMU: Sound Blaster emulation on AC97. Version: 1.0 beta3
Hello, world! device_type = 3
00:00:00.000 sc_ich.c      446 chip init : enable PCI io and busmaster
00:00:00.164 sc_ich.c      486 vend_id:1039 dev_id:7012 devtype:SIS7012 bmport:EA00 mixport:E000 irq:10
00:00:00.164 sc_ich.c      207 buffer init: pagetable:00100000 pcmoutbuf:00100100 size:4096
00:00:00.164 sc_ich.c      215 clear status bits
00:00:00.164 sc_ich.c      220 ACLink ON, set 2 channels
00:00:00.164 sc_ich.c      226 AC97 reset type: cold
00:00:00.164 sc_ich.c      235 AC97 reset timeout:1000
00:00:00.164 sc_ich.c      239 primary codec reset timeout:1000
00:00:00.164 sc_ich.c      250 unmute the output on SIS7012
00:00:00.164 sc_ich.c      255 chip init end
00:00:00.164 sc_ich.c      278 ac97 init end (vra:0)
Found sound card: ICH AC97
Real mode support: enabled.
Protected mode support: enabled.
OPL3 emulation enabled at port 388h.
Sound Blaster Pro emulation enabled at Adress: 220, IRQ: 7, DMA: 1
00:00:00.164 sc_ich.c      286 prepare playback: period_size_bytes:1024
00:00:00.164 sc_ich.c      294 dma stop timeout: 1000
00:00:00.164 sc_ich.c      301 dma stop timeout: 1000
00:00:00.164 sc_ich.c      311 unmute the output on SIS7012
00:00:00.164 sc_ich.c      340 AC97 front dac freq:48000 
00:00:00.164 sc_ich.c      375 prepare playback end
```

WIP patch that doesn't work attached (I can turn this into a pull request once it starts working somewhat): [sis7012-wip.patch](https://github.com/crazii/SBEMU/files/12736173/sis7012-wip.patch)

### PR DESCRIPTION
**Pull request by thp**
This is based on information from the Linux and FreeBSD AC97/ICH sound drivers, with some local testing and trial'n'error to recover from DMA underruns.

### CODE REVIEW

File: MPXPLAY/AU_CARDS/SC_ICH.C [hunk 1]
```diff
@@ -56,19 +63,18 @@
...
 
-#define ICH_DMABUF_MAX_PERIODS  32
-#define ICH_DMABUF_PERIODS   4
-#define ICH_MAX_CHANNELS     2
-#define ICH_MAX_BYTES        4
-#define ICH_DMABUF_ALIGN (ICH_DMABUF_MAX_PERIODS*ICH_MAX_CHANNELS*ICH_MAX_BYTES) // 256
+#define ICH_DMABUF_MAX_PERIODS  32 // number of entries in the Buffer Descriptor List
+#define ICH_DMABUF_PERIODS   4 // number of "used" entries in the Buffer Descriptor List
+#define ICH_BDL_ENTRY_SIZE (2 * sizeof(uint32_t))  // size of one entry in the Buffer Descriptor List
+#define ICH_DMABUF_ALIGN (ICH_DMABUF_MAX_PERIODS*ICH_BDL_ENTRY_SIZE) // 256
```
Comment (thp) [inline MPXPLAY/AU_CARDS/SC_ICH.C:77]: This is kind of unrelated to SIS7012 support, but during reading of the AC97 docs on OSDev, I found that some of these things look mislabeled (it works because 2 * sizeof(uint32_t) is the same as 2 * 4, even though the "2" doesn't have anything to do with channels. Those values are used for the Buffer Descriptor List.

File: MPXPLAY/AU_CARDS/SC_ICH.C [hunk 2]
```diff
@@ -177,10 +183,20 @@ static unsigned int snd_intel_buffer_init(struct intel_card_s *card,struct mpxpl
...
+ // Allocate Buffer Descriptor List + PCM output buffer in a single allocation
+ card->dm = MDma_alloc_cardmem(buffer_descriptor_list_size + card->pcmout_bufsize);
+
+ // buffer descriptor list requires ICH_BDL_ENTRY_SIZE alignment,
+ // but dos-allocmem gives 16 byte align (so we don't need alignment correction)
+ card->virtualpagetable = (uint32_t *)card->dm->linearptr;
+ card->pcmout_buffer = card->dm->linearptr + buffer_descriptor_list_size;
+
+ // DMA buffer written by MDma_writedata() and MDma_clearbuf()
+ aui->card_DMABUFF = card->pcmout_buffer;
```
Comment (thp) [inline MPXPLAY/AU_CARDS/SC_ICH.C:198]: Just like above, this is unrelated to SIS7012, but documents this part a little better.

File: MPXPLAY/AU_CARDS/SC_ICH.C [hunk 3]
```diff
@@ -322,7 +351,6 @@ static void snd_intel_prepare_playback(struct intel_card_s *card,struct mpxplay_
  snd_intel_write_32(card,ICH_PO_BDBAR_REG,(uint32_t)pds_cardmem_physicalptr(card->dm,table_base));
 
  snd_intel_write_8(card,ICH_PO_LVI_REG,(ICH_DMABUF_PERIODS-1)); // set last index
- snd_intel_write_8(card,ICH_PO_CIV_REG,0); // reset current index
```
Comment (thp) [inline MPXPLAY/AU_CARDS/SC_ICH.C:325]: The CIV register is read-only in AC97, so I removed writes to it.

File: MPXPLAY/AU_CARDS/SC_ICH.C [hunk 4]
```diff
@@ -598,23 +616,22 @@ static long INTELICH_getbufpos(struct mpxplay_audioout_info_s *aui)
    if(retry>1)
     continue;
    MDma_clearbuf(aui);
-   snd_intel_write_8(card,ICH_PO_LVI_REG,(ICH_DMABUF_PERIODS-1));
-   snd_intel_write_8(card,ICH_PO_CIV_REG,0);
```
Comment (thp) [inline MPXPLAY/AU_CARDS/SC_ICH.C:602]: The CIV register is read-only in AC97, so I removed writes to it.

**Comment by sezero** [comment]
Is this tested in mpxplay itself? (I guess a backport would be needed for it.)

**Comment by thp** [comment]
> Is this tested in mpxplay itself? (I guess a backport would be needed for it.)

Haven't backported it or tested it in MPXPlay. Should be easy to backport, although some `#ifdef SBEMU` lines make it a bit more difficult (just a little bit more effort, not impossible). Would be great to get some feedback from other users using SIS7012 if it actually works on their machines first :)

File: MPXPLAY/AU_CARDS/SC_ICH.C (hunk 3 above)
Comment (crazii) [reply MPXPLAY/AU_CARDS/SC_ICH.C:325]: Yeah I saw this too, but I didn't remove it, thought it wouldn't hurt. And yes remove it also wouldn't hurt.
